language: node_js

node_js:
  - '6'

notifications:
  slack:
    secure: Kqti4JvzIeu3wX66YkQ3oJ7I8h7pugeHqQpps5HrXB7esIGaw6POByZLsXWW9Jn6jNBYXNHy/5O17xb7+GOD3WC8Bf6WhGXa//K5S1nFP3VCQIy4EU4sqaVRft9twnEgP++6qpPF2eWLOUplNVTFZVLSQJhqnVWfxQEPX7RvjnyLvHaOjW85NXjW93dhjNIiFK0jTLG9PK62ylk2fjG8WncY6T9VFgONd1eJSRRjK/NIp/vEifC0vEG8OQyG1ukY0iW+aUdp4fOR4yeFFx1EJiPAMXM1vL+lgOlbxieYziOYJ+x1ZO+1iUiNR26uu8gZwOnUGVCD7PzKmslhsQpBMRk0iTTR5hGMf7WWgfOYzTFRYI5A2VkJjScTCLjZLXvulbB5L7g4k31Ymx8z5dML/SBKBnFM2aEJZW+EoDx8dwsky/DwA0KS9Y2/Y9KPXavMlfsoBh9h0GAA4eGern906FkaXBbuec/q4TIZiS8Fw7TGey5sBx5mWT6penK7zSb3bAehVNUJADaTZrzF/ybb+zy/NBcrHv2Q//D8B76dTuLeJh30KCPfVBUDkoKTrWEA/llzFaKGx0MA9Tu107U3+6KEPK/xQb9++GPUn/8p1Hc3MRsV/GnE8PwR8Fr9EqdtbhgD7DaB/1qLsBubDyg21uGxGt2b+pdkZAaDXIb6wzg=

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/i
    - /^hotfix\/.*$/i

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install yarn

install:
  - yarn install

after_success:
  - yarn clean
