language: node_js

node_js:
  - '6'

notifications:
  slack:
    rooms:
    - indaym:GAD0nh4Bli786nr5Inogl8WF#front-end-ci

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/i
    - /^hotfix\/.*$/i

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install yarn

install:
  - yarn install

after_success:
  - yarn clean
